### ISSUE TITLE
Add latest c5 version

### ISSUE THREAD

**Issue by 1stthomas** [concrete5-community/docker5#17]
c5-8.5.5 has been released, but is not implemented here.

To fix this I found: https://github.com/concrete5-community/docker5/commit/bf03ce6197558c0b0342ca13dc648828e411c5cb#diff-5c3fa597431eda03ac3339ae6bf7f05e1a50d6fc7333679ec38e21b337cb6721

Are these the only files to touch? If so I could do a PR if you'd like.

**Comment by mlocati** [comment]
Yep! See #18

**Comment by 1stthomas** [comment]
thanks!
