### ISSUE TITLE
Latest image fails to start nginx

### ISSUE THREAD

**Issue by rulatir** [concrete5-community/docker5#24]
Steps to reproduce:
```
$ docker run --rm -it -p 8080:80 -p 33306:3306 ghcr.io/concrete5-community/docker5:9.1.1-full
```

Expected:
```
Starting MariaDB... done.
Starting Nginx... done.
Starting PHP-FPM... done.
```
... and a running container.

Actual:
```
Starting MariaDB... done.
Starting Nginx... 
FAILED!.
Starting PHP-FPM... done.
Failed to start services
```
... and the container exits.

By overriding the entrypoint to get into the container's shell, I issued `ccm-service start` with the same result, and found this in `/var/log/nginx/error.log`:
```
2022/09/09 19:00:13 [emerg] 332#332: socket() [::]:80 failed (97: Address family not supported by protocol)
```
Possibly relevant: the host is IP4-only. Is that an exotic scenario? Many desktop linux users disable IP6.

**Comment by rulatir** [comment]
Looks like a docker issue, but apparently it has been [fixed](https://github.com/moby/libnetwork/pull/2635) back in April? My docker is 20.10.17.

**Comment by mlocati** [comment]
I don't know: everything is working fine for me... (docker 20.10.17,1 on Windows).
