### ISSUE TITLE
Trouble Installing PHP Module (Mongodb)

### ISSUE THREAD

**Issue by DaveMeade** [concrete5-community/docker5#25]
Can anyone provide guidance on installing additional PHP modules when using this repo? I'm working on a custom package that needs mongodb.

I'm running the container with the command:
`docker run --rm -it -p 80:80 -p 33306:3306 -v d/mypackage_handle:/app/packages/mypackage_handle -e "CCM_PHP_VERSION=7.4" -e "CCM_COMPOSER_VERSION=2" ghcr.io/concrete5-community/docker5:9.1`

At the bash shell of the container, I've tried installing mongodb via command line, enabling it in php.ini, and restarting services but when I attempt to run compose install in my package directory, it still errors out saying mongodb "`is missing from your system. Install or enable PHP's mongodb extension.`".

When I running `php --ini` it begins with the Warning:

`PHP Warning:  PHP Startup: Unable to load dynamic library 'mongodb.so' (tried: /usr/lib/php/20190902/mongodb.so (/usr/lib/php/20190902/mongodb.so: cannot open shared object file: No such file or directory), /usr/lib/php/20190902/mongodb.so.so (/usr/lib/php/20190902/mongodb.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0`

And running `find / -name mongodb.so` shows the file is in fact at
`/usr/lib/php/20210902/mongodb.so`

(Copying the file to /usr/lib/php/20190902/mongodb.so does not help)

Thanks in advance

**Comment by mlocati** [comment]
Here's what I'd do:

1. start the container (as you did):
   ```
   docker run --rm -it -p 80:80 -p 33306:3306 -v d/mypackage_handle:/app/packages/mypackage_handle -e "CCM_PHP_VERSION=7.4" -e "CCM_COMPOSER_VERSION=2" ghcr.io/concrete5-community/docker5:9.1
   ```
2. refresh the list of system packages
   ```
   apt update
   ```
3. install the MongoDB PHP extension
   ```
   apt install -y php7.4-mongodb
   ```
4. restart PHP FPM
   ```
   ccm-service restart php-fpm
   ```

Now you should have the PHP mongodb up and running.
