### ISSUE TITLE
Cannot use latest 9.2.2 release

### ISSUE THREAD

**Issue by 1stthomas** [concrete5-community/docker5#49]
I just tried to get the `9.2.2` image of concreteCMS (`ghcr.io/concrete5-community/docker5:9.2.2`).
Got an error: `docker: Error response from daemon: manifest unknown.`
`ghcr.io/concrete5-community/docker5:9.2.2-full` doesn't work either.
Looking at https://github.com/concrete5-community/docker5/pkgs/container/docker5 I can't see an image of the `9.2.2` version.

(I thought the image creation should be automated when a new version was released. If so this process didn't work as expected)

**Comment by mlocati** [comment]
Thanks for the report!

I'm working on this, expect a fix soon 😉

**Comment by mlocati** [comment]
Fixed by #51 (made possible thanks to #50)

**Comment by mlocati** [comment]
> I thought the image creation should be automated when a new version was released

It works :wink: - see #53
